### PR TITLE
WIP: Results Translations

### PR DESCRIPTION
**Pull request by KingSit3**

### CODE REVIEW

**Comment by Klrfl** [comment]
Are you done yet? Can I merge it into main?

**Comment by KingSit3** [comment]
> Are you done yet? Can I merge it into main?

not yet, but you can merge it into main, I'm kinda busy lately

**Comment by Klrfl** [comment]
Okay. You can always make another pull request👍

**Comment by KingSit3** [comment]
> Okay. You can always make another pull request👍

from now on, i will always make PT even it's still WIP

**Pull request merged**
